name: surface-coatings
channels:
  - conda-forge
dependencies:
  - mbuild
  - ele
  - foyer
  - forcefield-utilities
  - gmso
  - pip
  - numpy
  - py3dmol
  - python >=3.7
  - rdkit
  - scipy
  - freud
  - pytest
