name: surface-coatings
channels:
  - conda-forge
dependencies:
  - mbuild>=0.16.3
  - ele
  - foyer>=0.12.0
  - forcefield-utilities>=0.2
  - gmso>=0.11
  - pip
  - numpy<1.25
  - py3dmol
  - python >=3.9
  - rdkit
  - scipy
  - freud
  - pytest
