name: Python Package using Conda

on:
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  test:
    name: Unit Test on ${{ matrix.os  }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
    - uses: mamba-org/provision-with-micromamba@main
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
        extra-specs: | 
          python=${{ matrix.python-version }}
        channels: conda-forge, defaults
        activate-environment: surface-coatings
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install -e . --no-deps
        conda list
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest -v --color=yes surface_coatings/tests/
